-- Weekly Planner schema for Supabase.
-- Paste this into the SQL editor of your Supabase project and run it once.

-- ── Tables ───────────────────────────────────────────────────
create table if not exists public.events (
  id text primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  title text not null,
  description text,
  location text,
  start timestamptz not null,
  "end" timestamptz not null,
  all_day boolean not null default false,
  category_id text,
  tags text[],
  recurrence jsonb,
  recurrence_exceptions text[],
  reminders jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id text primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  name text not null,
  color text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.goals (
  id text primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  title text not null,
  description text,
  week_start text not null,
  done boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.habits (
  id text primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  name text not null,
  emoji text,
  color text not null,
  target integer not null,
  completions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

create index if not exists events_user_idx on public.events(user_id);
create index if not exists categories_user_idx on public.categories(user_id);
create index if not exists goals_user_idx on public.goals(user_id);
create index if not exists habits_user_idx on public.habits(user_id);

-- ── Row-level security ──────────────────────────────────────
alter table public.events enable row level security;
alter table public.categories enable row level security;
alter table public.goals enable row level security;
alter table public.habits enable row level security;
alter table public.user_settings enable row level security;

drop policy if exists "own_events" on public.events;
create policy "own_events" on public.events
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own_categories" on public.categories;
create policy "own_categories" on public.categories
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own_goals" on public.goals;
create policy "own_goals" on public.goals
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own_habits" on public.habits;
create policy "own_habits" on public.habits
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own_settings" on public.user_settings;
create policy "own_settings" on public.user_settings
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ── Sharing: planner_members + planner_invites ───────────────
-- planner_members lists which other users have access to each owner's planner.
-- planner_invites are one-time tokens generated by an owner; accepting a token
-- inserts into planner_members.

create table if not exists public.planner_members (
  owner_id uuid not null references auth.users(id) on delete cascade,
  member_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'editor' check (role in ('editor', 'viewer')),
  owner_email text,
  member_email text,
  created_at timestamptz not null default now(),
  primary key (owner_id, member_id)
);

create index if not exists planner_members_member_idx on public.planner_members(member_id);

create table if not exists public.planner_invites (
  token text primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  owner_email text,
  role text not null default 'editor' check (role in ('editor', 'viewer')),
  expires_at timestamptz not null,
  used_by uuid references auth.users(id) on delete set null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists planner_invites_owner_idx on public.planner_invites(owner_id);

alter table public.planner_members enable row level security;
alter table public.planner_invites enable row level security;

drop policy if exists "members_visible" on public.planner_members;
create policy "members_visible" on public.planner_members
  for select using (auth.uid() = owner_id or auth.uid() = member_id);

drop policy if exists "members_owner_writes" on public.planner_members;
create policy "members_owner_writes" on public.planner_members
  for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

drop policy if exists "members_self_delete" on public.planner_members;
create policy "members_self_delete" on public.planner_members
  for delete using (auth.uid() = member_id);

-- Owners manage their own invites; recipients can look up a single token they hold.
drop policy if exists "invites_owner_all" on public.planner_invites;
create policy "invites_owner_all" on public.planner_invites
  for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

drop policy if exists "invites_anyone_lookup" on public.planner_invites;
create policy "invites_anyone_lookup" on public.planner_invites
  for select using (true);

-- ── Expand existing-table RLS to allow members ──────────────
-- Replace the "own_X" policies with versions that also accept members.

drop policy if exists "own_events" on public.events;
create policy "events_access" on public.events
  for all
  using (
    auth.uid() = user_id
    or exists (select 1 from public.planner_members m where m.owner_id = events.user_id and m.member_id = auth.uid())
  )
  with check (
    auth.uid() = user_id
    or exists (select 1 from public.planner_members m where m.owner_id = events.user_id and m.member_id = auth.uid() and m.role = 'editor')
  );

drop policy if exists "own_categories" on public.categories;
create policy "categories_access" on public.categories
  for all
  using (
    auth.uid() = user_id
    or exists (select 1 from public.planner_members m where m.owner_id = categories.user_id and m.member_id = auth.uid())
  )
  with check (
    auth.uid() = user_id
    or exists (select 1 from public.planner_members m where m.owner_id = categories.user_id and m.member_id = auth.uid() and m.role = 'editor')
  );

drop policy if exists "own_goals" on public.goals;
create policy "goals_access" on public.goals
  for all
  using (
    auth.uid() = user_id
    or exists (select 1 from public.planner_members m where m.owner_id = goals.user_id and m.member_id = auth.uid())
  )
  with check (
    auth.uid() = user_id
    or exists (select 1 from public.planner_members m where m.owner_id = goals.user_id and m.member_id = auth.uid() and m.role = 'editor')
  );

drop policy if exists "own_habits" on public.habits;
create policy "habits_access" on public.habits
  for all
  using (
    auth.uid() = user_id
    or exists (select 1 from public.planner_members m where m.owner_id = habits.user_id and m.member_id = auth.uid())
  )
  with check (
    auth.uid() = user_id
    or exists (select 1 from public.planner_members m where m.owner_id = habits.user_id and m.member_id = auth.uid() and m.role = 'editor')
  );

-- user_settings stays per-user (each user keeps their own settings even on a shared planner).

-- ── Atomic invite acceptance (RPC) ───────────────────────────
-- Called by an authenticated user with a token; on success creates a member row.
create or replace function public.accept_planner_invite(invite_token text)
returns table(owner_id uuid, owner_email text, role text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner uuid;
  v_owner_email text;
  v_role text;
  v_email text;
  v_self uuid := auth.uid();
begin
  if v_self is null then
    raise exception 'not authenticated';
  end if;

  select i.owner_id, i.owner_email, i.role
    into v_owner, v_owner_email, v_role
  from public.planner_invites i
  where i.token = invite_token and i.expires_at > now() and i.used_by is null;

  if v_owner is null then
    raise exception 'invite invalid or expired';
  end if;

  if v_owner = v_self then
    raise exception 'cannot accept your own invite';
  end if;

  select email into v_email from auth.users where id = v_self;

  insert into public.planner_members(owner_id, member_id, role, owner_email, member_email)
  values (v_owner, v_self, v_role, v_owner_email, v_email)
  on conflict (owner_id, member_id) do update set role = excluded.role;

  update public.planner_invites
    set used_by = v_self, used_at = now()
    where token = invite_token;

  return query select v_owner, v_owner_email, v_role;
end;
$$;

grant execute on function public.accept_planner_invite(text) to authenticated;

-- ── Realtime additions ──────────────────────────────────────
alter publication supabase_realtime add table public.events;
alter publication supabase_realtime add table public.categories;
alter publication supabase_realtime add table public.goals;
alter publication supabase_realtime add table public.habits;
alter publication supabase_realtime add table public.user_settings;
alter publication supabase_realtime add table public.planner_members;
